<div class="col-lg-3 visible-lg">
    <article class="thisbox">
        <div class="head">
            <span>Profil</span>
        </div>
        <div class="body">
            <p>
               <!-- <img class="img-thumbnail " alt="" src="/img/profil2.jpg"/> -->
            </p>
            <p class="text-muted">
                Geboren und aufgewachsen in der kleinen Stadt Saalfeld, begann ich 2004 mir meine erste Kamera zu kaufen und zu fotografieren.
                Ausgerüstet mit einer kleinen Digitalkamera und einer Spiegelreflexkamera zog ich los. 
                Doch bald reichte das Knipsen von Gegenständen und einigen verschiedenen Landschaften nicht mehr und ich begann mich im 
                Internet und Büchern über Kameras und Techniken der Fotografie zu informieren. 
                Dann kam ich durch einen Freund das erste Mal in Berührung mit der Portraitfotografie, die mich so sehr begeistert hat, dass ich bis heute dabei geblieben bin.
                Wieder half mir das Internet bei der Auswahl der Technik und dem Umgang mit dem Thema.
                Da ich das alles intensiv nebenbei mache, bin ich zeitlich oft sehr eingespannt.
                Ich besitze auch kein eigenes Studio, was aber kein Problem ist.
                Ich schätze die Freiheit in die Natur und Stadt zu gehen, die Herausforderung das Licht zu nutzen oder es immer wieder neu 
                zu gestalten, um immer wieder neues zu entdecken.
            </p>
        </div>
    </article>
</div>