<div class="row">
    <div class="col-lg-9 col-md-12">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <article class="thisbox">
                    <div class="head">
                        <span><?php echo $this->entry->title; ?></span>
                        <span class="pull-right "><?php echo $this->entry->created; ?></span>
                    </div>
                    <div class="body">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 slide">
                                <?php foreach ($this->entry->pictures as $pic) { ?>
                                    <p class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                        <a href="<?php echo $pic['original']; ?>" class="fancybox-thumb" rel="news-<?php echo $this->entry->id; ?>" >
                                            <img class="img-thumbnail " alt=""
                                                 src="<?php echo $pic['thumb']; ?>">
                                        </a>
                                    </p>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
    <div class="col-lg-3 visible-lg">
        <article class="thisbox">
            <div class="head">
                <span>Profil</span>
            </div>
            <div class="body">
                <p>
                   <!-- <img class="img-thumbnail " alt="" src="/img/profil2.jpg"/> -->
                </p>
                <p class="text-muted">
                    Geboren und aufgewachsen in der kleinen Stadt Saalfeld, begann ich 2004 mir meine erste Kamera zu kaufen und zu fotografieren.
Ausgerüstet mit einer kleinen digital Kamera und einer Spiegelreflexkamera zog ich los. 
Doch bald reichte das knipsen von Gegenständen und einigen verschiedenen Landschaften nicht mehr und ich begann mich im Internet und Büchern über Kameras und techniken der Fotografie zu informieren. 
Dann kam ich durch einen Freund das erste mal in berührung mit der Portraitfotografie, die mich so sehr begeistert hat, das ich bis heute dabei geblieben bin.
Wieder half mir das Internet bei der auswahl der Technik und den umgang mit dem Thema.
Da ich das alles intensiv nebenbei mache, bin ich zeitlich oft sehr eingespannt.
Ich besitze auch kein eigenes studio, was aber kein problem ist.
Ich schätze die Freiheit in die Natur und Stadt zu gehen, die herausforderung das licht zu nutzen oder es immerwieder neu zu gestalten, um immer wieder neues zu entdeckt
                </p>
            </div>
        </article>
    </div>
</div>