<div class="row lightbox">
    <h1 class="text-center"><?php echo $this->label;?></h1>
    <?php
    foreach ($this->entry as $entry):
        $url = $this->url(array(
            'controller' => 'index',
            'action' => 'gallery',
            'id' => $entry->getId()
                ), 'gallery');
        $title = $entry->getTitle();
        if($entry->getCreated() != '0000-00-00') {
            $title .= "<br>".$entry->getCreated();
        }
        ?>
        <div class="col-md-3 col-sm-3 col-xs-12 image">
            <a href="<?php echo $url; ?>">
                <img src="<?php echo $entry->getPreview();?>" class="boxed" data-pin-no-hover="true">
                <div class="overlay"><?php echo $title; ?></div>
            </a>
        </div>
    <?php endforeach; ?>
</div>
