<?php
$galleries = array(
    array(
        'id' => 1,
        'name' => 'Caro',
        'pic' => "/pictures/beitragsbild-480x640.png"
    ),
    array(
        'id' => 1,
        'name' => 'Janine',
        'pic' => "/pictures/3100swweb-480x640.jpg"
    ),
    array(
        'id' => 1,
        'name' => 'Pauline',
        'pic' => "/pictures/beitragsbild-480x640.png"
    ),
    array(
        'id' => 1,
        'name' => 'Die Brüder König',
        'pic' => "/pictures/beitragsbild-480x640.png"
    ),
    array(
        'id' => 1,
        'name' => 'Caro',
        'pic' => "/pictures/beitragsbild-480x640.png"
    ),
);
?>

<div class="row lightbox">
    <h1 class="text-center">Zimt & Zucker</h1>
    <div class="col-md-12">
    <p>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    </p>
    </div>
    <?php foreach ($galleries as $gallery): ?>
        <div class="col-md-3 col-sm-3 col-xs-12 image">
            <img src="<?php echo $gallery['pic']; ?>" class="boxed" data-pin-no-hover="true">
            <div class="overlay"><?php echo $gallery['name'];?></div>
        </div>
    <?php endforeach; ?>
</div>
