<div class="row lightbox">
    <div class="col-md-4 col-sm-4 col-xs-12">
        <img src="http://placehold.it/316x150/e5e3d7&text=Luftsprung" class="boxed" data-pin-no-hover="true">
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12">
        <img src="http://placehold.it/316x150/e5e3d7&text=Luftsprung" class="boxed" data-pin-no-hover="true">
    </div>
    <div class="col-md-4 col-sm-4 col-xs-12">
        <img src="http://placehold.it/316x150/e5e3d7&text=Luftsprung" class="boxed" data-pin-no-hover="true">
    </div>
    <div class="col-md-12 col-xs-12">
        <img src="http://placehold.it/1000x450/e5e3d7&text=Luftsprung" class="boxed" data-pin-no-hover="true">
    </div>
</div>
