<div class="row">
    <div class="col-md-4">
        <span href="#" class="thumbnail">
            <img src="http://placehold.it/316x150/e5e3d7&text=Luftsprung">
        </span>
    </div>
    <div class="col-md-4">
        <span href="#" class="thumbnail">
            <img src="http://placehold.it/316x150/e5e3d7&text=Luftsprung">
        </span>
    </div>
    <div class="col-md-4">
        <span href="#" class="thumbnail">
            <img src="http://placehold.it/316x150/e5e3d7&text=Luftsprung">
        </span>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
       <span href="#" class="thumbnail">
            <img src="http://placehold.it/1000x450/e5e3d7&text=Luftsprung">
        </span>
    </div>
</div>
