<div class="row lightbox">
    <div class="col-md-12">
        <h3>Kontakt</h3>
        <div class="row ">
            <div class="col-lg-12 col-md-12">
                <p class="text-muted center-block">
                    <br />
                    Vielen Dank für den Besuch auf meiner Website<br />
                    Du möchtest gerne mehr über meine Shootings erfahren, oder hast andere Fragen?<br /> Dann schick mir eine kurze Nachricht
                    und du erhälst kurzfristig eine Antwort von mir. 
                </p>
                <br />
                <?php echo $this->partial('forms/kontakt.phtml', array('form' => $this->form)); ?>
            </div>
        </div>
    </div>
</div>
