<div class="row lightbox">
    <div class="col-md-12">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <div class="well well-sm">
                        <form name="comment" role="form" 
                              id="<?php print $this->escape($this->form->getName()) ?>" 
                              action="<?php print $this->escape($this->form->getAction()) ?>" 
                              method="<?php print $this->escape($this->form->getMethod()) ?>">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label for="name">
                                            Name</label>
                                        <input type="text" class="form-control" id="name" name="name" 
                                               placeholder="Dein Name" 
                                               required="required"
                                               value="<?php echo $this->form->getElement('name')->getValue() ?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="email">
                                            Email Adresse</label>
                                        <div class="input-group">
                                            <input type="email" class="form-control" id="mail" name="mail" 
                                                   placeholder="eMail" 
                                                   required="required"
                                                   value="<?php echo $this->form->getElement('mail')->getValue() ?>">
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="subject">
                                            Betreff</label>
                                        <select id="subject" name="subject" class="form-control" required="required">
                                            <option value="na" selected="">wähle:</option>
                                            <option value="service">Allgemeine Fragen</option>
                                            <option value="shooting">Shooting Termin</option>
                                            <option value="error">Fehler auf der Seite</option>
                                        </select>
                                    </div>
                                    <div class="form-group" id="dateelement">
                                        <label for="datum">
                                            Datum
                                        </label>
                                        <input type="text" class="form-control datepicker" id="datum" name="datum">
                                    </div>
                                </div>
                                <div class="col-md-7">
                                    <div class="form-group">
                                        <label for="name">
                                            Nachricht</label>
                                        <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                                  placeholder="Nachricht"></textarea>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                                        Senden</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-4">
                    <form>
                        <legend><span class="glyphicon glyphicon-globe"></span> Mein Büro</legend>
                        <address>
                            <strong>Luftsprung</strong><br>
                            Saalfelder Chausee 12<br>
                            07318 Saalfeld<br>
                            <abbr title="Telefon">
                                P:</abbr>
                            (123) 456-7890
                        </address>
                        <address>
                            <strong>eMail</strong><br>
                            <a href="mailto:nadin@luftsprung.de">nadin@luftsprung.de</a>
                        </address>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>