<div class="row">
    <div class="col-lg-9 col-md-12">
        <?php foreach ($this->news as $news) { 
            $url = $this->url(array(
                'controller'    => 'index',
                'action'        => 'news',
                'id'            => $news->id
            ),'news', true);
            ?>
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <article class="thisbox">
                        <div class="head <?php if($news->active == 0) echo 'inactive';?>">
                            <span><a href="<?php echo $url; ?>"><?php echo $news->title; ?></a></span>
                            <span class="pull-right "><?php echo $news->created; ?></span>
                        </div>
                        <div class="body">
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <p class="text-muted">
                                        <?php 
                                        $bbcode = Zend_Markup::factory('Bbcode');
                                        echo nl2br($bbcode->render($news->teaser)); 
                                        ?>
                                    </p>
                                </div>
                                <div class="col-lg-12 col-md-12 slide">
                                    <?php foreach ($news->pictures as $pic) { ?>
                                        <p class="col-lg-4 col-md-4 col-sm-4 col-xs-6">
                                            <a href="<?php echo $pic['original']; ?>" class="fancybox-thumb" rel="news-<?php echo $news->id;?>" >
                                                <img class="img-thumbnail " alt=""
                                                     src="<?php echo $pic['thumb']; ?>">
                                            </a>
                                        </p>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                        <?php
                        try{
                            $comments = $this->comments->findComments($news->id);
                            $this->form->setAction($this->url());
                            $this->form->getElement('newsid')->setValue($news->id);
                        } catch (Exception $e) {
                            Zend_Debug::dump($e->getMessage());
                        }
                        ?>
                        <footer>
                            <span class="pointer glyphicon glyphicon-comment" data-toggle="collapse" data-target="#comments-<?php echo $news->id;?>"> 
                                <?php echo count($comments) ?> Kommentare
                            </span> 
                            <div class="row collapse <?php echo $this->commentsubmit ? "in" : "" ?>" id="comments-<?php echo $news->id;?>">
                                <hr>
                                    <?php
                                    foreach ($comments as $comment) {
                                        $class = "";
                                        $classenable = "disabled";
                                        $classdisable = "";
                                        if ($comment->active == 0 && Zend_Auth::getInstance()->hasIdentity()) {
                                            $class = "inactive";
                                            $classenable = "";
                                            $classdisable = "disabled";
                                        } elseif (Zend_Auth::getInstance()->hasIdentity()) {
                                            $class = "";
                                        }
                                        ?>
                                            <div class="thisbox">
                                            <div class="head <?php echo $class; ?>">
                                                <span><?php echo $comment->name ?></span>
                                                <span class="pull-right" 
                                                      data-toggle="tooltip" 
                                                      data-placement="top" 
                                                      title 
                                                      data-original-title="<?php echo $comment->created; ?>">
                                                    <?php echo $comment->createddate; ?>
                                                </span>
                                            </div>
                                            <div class="body">
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12">
                                                        <p>
                                                        <?php echo nl2br($comment->comment); ?>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                                <?php
                                                if (Zend_Auth::getInstance()->hasIdentity()) {
                                                    $enableNews = $this->url(array(
                                                        'controller' => 'index',
                                                        'action' => 'editnews',
                                                        'c' => 'enable',
                                                        'comment' => $comment->id
                                                    ));
                                                    $disableNews = $this->url(array(
                                                        'controller' => 'index',
                                                        'action' => 'editnews',
                                                        'c' => 'disable',
                                                        'comment' => $comment->id
                                                    ));
                                                    $deleteNews = $this->url(array(
                                                        'controller' => 'index',
                                                        'action' => 'editnews',
                                                        'c' => 'delete',
                                                        'comment' => $comment->id
                                                    ));
                                                    ?>
                                                <div class="col-lg-12 col-md-12">
                                                    <!-- Single button -->
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
                                                            Administration <span class="caret"></span>
                                                        </button>
                                                        <ul class="dropdown-menu" role="menu">
                                                            <li class="<?php echo $classenable ?>"><a href="<?php echo $enableNews; ?>">Beitrag freigaben</a></li>
                                                            <li class="<?php echo $classdisable ?>"><a href="<?php echo $disableNews; ?>">Beitrag sperren</a></li>
                                                            <li class="divider"></li>
                                                            <li><a href="<?php echo $deleteNews; ?>">Beitrag löschen</a></li>
                                                        </ul>
                                                    </div>
                                                </div>							
                                                <?php } ?>
                                            </div>
                                            <?php } ?>
                            <?php echo $this->partial('forms/comment.phtml', array('form' => $this->form)); ?>
                            </div>
                        </footer>
                    </article>
                </div>
            </div>

        <?php
        }
        echo $this->paginationControl($this->news, 'Sliding', 'my_default_pager.phtml');
        ?>
    </div>
    <?php
    echo $this->render('widgets/profile.phtml');
    ?>
</div>