<h1><?php echo $this->tag; ?></h1>

<div class="row">
    
    <?php foreach($this->entries as $entry):?>
    <div class="col-md-4 col-sm-4 col-xs-12">
        <img src="http://placehold.it/316x150/e5e3d7&text=<?php echo $entry->getTitle();?>" class="boxed" data-pin-no-hover="true">
    </div>
    <?php endforeach;?>
    <div class="col-md-4">
        <a data-toggle="modal" data-target="#galleryModal">
            <div class="boxed">
                <div>
                    <span class=" glyphicon glyphicon-plus center-block" style="font-size: 45px;"></span>
                </div>
                <br>
                <p class="text-primary center-block text-center">Neue Gallerie</p>
            </div>
        </a>
    </div>
</div>