<div class="row">
    <?php foreach ($this->entries as $entry): 
        $url = "/json/loadgalleriemodal/gallerieid/".$entry->getId();
        ?>
    <div class="col-md-3 col-sm-3 col-xs-12 image">
        <a data-modal="gallerymodal" data-target="#galleryModal" data-remote="<?php echo $url;?>">
            <img src="<?php echo $entry->getPreview();?>" class="boxed" data-pin-no-hover="true">
            <div class="overlay">
                <?php echo $entry->getTitle(); ?> <br>
                <?php echo $entry->getCreated(); ?>
            </div>
        </a>
    </div>
    <?php endforeach; ?>
    <div class="col-md-3">
        <a data-modal="gallerymodal" data-target="#galleryModal" data-remote="/json/loadgalleriemodal/tag/<?php echo $this->tag;?>">
            <div class="boxed">
                <div>
                    <span class=" glyphicon glyphicon-plus center-block" style="font-size: 45px;"></span>
                </div>
                <br>
                <p class="text-primary center-block text-center">Neue Gallerie</p>
            </div>
        </a>
    </div>
</div>