<h1><?php echo $this->tag; ?></h1>

<div class="row gridster">
    <div class="col-md-3" data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <img src="http://placehold.it/316x150/e5e3d7&text=Box_1" class="boxed">
  </div>
    <div class="col-md-3" data-row="1" data-col="1" data-sizex="1" data-sizey="1">
        <img src="http://placehold.it/316x150/e5e3d7&text=Box_2" class="boxed" data-pin-no-hover="true">
    </div>
    <div class="col-md-3" data-row="1" data-col="1" data-sizex="1" data-sizey="1">
        <img src="http://placehold.it/316x150/e5e3d7&text=Box_3" class="boxed" data-pin-no-hover="true">
    </div>
</div>