<!-- Modal -->
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"><?php echo $this->entry->getTitle();?></h4>
            </div>
            <input type="hidden" name="tag" id="gallerytag" value="" >
            <input type="hidden" name="galleryid" id="galleryid" value="" >
            <div class="modal-body">
                <form role="form" class="form-horizontal">
                    <div class="form-group">
                        <label for="galleriename" class="col-sm-2 control-label">Galleriename</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="galleriename" placeholder="Galleriename" value="<?php echo $this->entry->getTitle();?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="datum" class="col-sm-2 control-label">Datum</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control datepicker" id="datum" value="<?php echo $this->entry->getCreated();?>">
                        </div>
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" id="updateGallery" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>