<!-- Modal -->
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel"><?php echo $this->entry->getTitle(); ?></h4>
        </div>
        <div class="modal-body">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#meta" data-toggle="tab">Basis</a></li>
                <?php if(!$this->entry->getId()):?>
                <li class="disabled disabledTab"><a href="#entry" data-toggle="tab">Eintrag</a></li>
                <?php else: ?>
                <li><a href="#entry" data-toggle="tab">Eintrag</a></li>
                <?php endif;?>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade in active" id="meta">
                    <p>
                    <form role="form" class="form-horizontal" id="Galleryform" action="/admin/addgallery">
                        <input type="hidden" name="tag" id="gallerytag" value="<?php echo $this->tag; ?>" >
                        <input type="hidden" name="galleryid" id="galleryid" value="<?php echo $this->entry->getId(); ?>" >
                        <div class="form-group">
                            <label for="galleriename" class="col-sm-2 control-label">Galleriename</label>
                            <div class="col-sm-3">
                                <input type="text" class="form-control" id="galleriename" placeholder="Galleriename" value="<?php echo $this->entry->getTitle(); ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="datum" class="col-sm-2 control-label">Datum</label>
                            <div class="col-sm-2">
                                <input type="text" class="form-control datepicker" id="datum" value="<?php echo $this->entry->getCreated(); ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group col-sm-4">
                                <input type="text" class="form-control" id="preview" value="<?php echo $this->entry->getPreview();?>">
                                <span class="input-group-btn">
                                    <a data-toggle="modal" class="btn btn-default" data-target="#filemanagerModal">Galleriebild wählen</a>
                                </span>
                            </div>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" id="delete"> Gallerie löschen
                            </label>
                        </div>
                    </form>
                </p>
                </div>
                <div class="tab-pane fade" id="entry">
                    <textarea id="galleryentry"><?php echo $this->entry->getPost();?></textarea>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" id="updateGallery" class="btn btn-primary">Save changes</button>
        </div>
    </div>
</div>