<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="http://placehold.it/320x150" alt="">
        <div class="caption">
            <h4 class="pull-right"><?php echo $this->article->getPrice(); ?></h4>
            <h4><a href="#"><?php echo $this->article->getName(); ?></a>
            </h4>
            <p>
                <?php echo $this->article->getEntry(); ?>
            </p>
        </div>
    </div>
</div>