<?php
$url = $this->url(array(
            'controller' => 'shop',
            'action' => 'product',
            'id' => $this->article->getId()
                ), 'default');
?>
<div class="col-sm-4 col-lg-4 col-md-4 product">
    <div class="thumbnail">
        <img src="http://placehold.it/320x150" alt="">
        <div class="caption">
            <h4 class="pull-right"><span class="glyphicon glyphicon-euro"></span> <?php echo $this->article->getPrice(); ?></h4>
            <h4><a href="<?php echo $url;?>"><?php echo $this->article->getName(); ?></a>
            </h4>
            <p>
                <?php echo $this->article->getEntry(); ?>
            </p>
        </div>
    </div>
</div>