<div class="row lightbox">
    <div class="col-md-12">
        <div class="container">
            <div class="row">
                <div class="btn-group btn-breadcrumb">
                    <a href="#" class="btn btn-primary">Warenkorb</a>
                    <a href="#" class="btn btn-default disabled">Kundendaten</a>
                    <a href="#" class="btn btn-default disabled">Zahlung</a>
                    <a href="#" class="btn btn-default disabled">Bestellung prüfen</a>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <div class="row">
                        <div class="col-xs-6">
                            <h5><span class="glyphicon glyphicon-shopping-cart"></span> Warenkorb</h5>
                        </div>
                        <div class="col-xs-3 pull-right">
                            <button type="button" class="btn btn-primary btn-sm btn-block">
                                <span class="glyphicon glyphicon-share-alt"></span> Einkauf fortsetzen
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <?php foreach($this->cart as $product):
                    //Zend_Debug::dump($product);
                    ?>
                <div class="row">
                    <div class="col-xs-2"><img class="img-responsive" src="http://placehold.it/100x70">
                    </div>
                    <div class="col-xs-4">
                        <h4 class="product-name"><strong><?php ?></strong></h4><h4><small>Product description</small></h4>
                    </div>
                    <div class="col-xs-6">
                        <div class="col-xs-6 text-right">
                            <h6><strong>25.00 <span class="text-muted">x</span></strong></h6>
                        </div>
                        <div class="col-xs-4">
                            <input type="text" class="form-control input-sm" value="1">
                        </div>
                        <div class="col-xs-2">
                            <button type="button" class="btn btn-link btn-xs">
                                <span class="glyphicon glyphicon-trash"> </span>
                            </button>
                        </div>
                    </div>
                </div>
                <hr>
                <?php endforeach;?>
                <div class="row">
                    <div class="col-xs-2"><img class="img-responsive" src="http://placehold.it/100x70">
                    </div>
                    <div class="col-xs-4">
                        <h4 class="product-name"><strong>Product name</strong></h4><h4><small>Product description</small></h4>
                    </div>
                    <div class="col-xs-6">
                        <div class="col-xs-6 text-right">
                            <h6><strong>25.00 <span class="text-muted">x</span></strong></h6>
                        </div>
                        <div class="col-xs-4">
                            <input type="text" class="form-control input-sm" value="1">
                        </div>
                        <div class="col-xs-2">
                            <button type="button" class="btn btn-link btn-xs">
                                <span class="glyphicon glyphicon-trash"> </span>
                            </button>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-xs-2"><img class="img-responsive" src="http://placehold.it/100x70">
                    </div>
                    <div class="col-xs-4">
                        <h4 class="product-name"><strong>Product name</strong></h4><h4><small>Product description</small></h4>
                    </div>
                    <div class="col-xs-6">
                        <div class="col-xs-6 text-right">
                            <h6><strong>25.00 <span class="text-muted">x</span></strong></h6>
                        </div>
                        <div class="col-xs-4">
                            <input type="text" class="form-control input-sm" value="1">
                        </div>
                        <div class="col-xs-2">
                            <button type="button" class="btn btn-link btn-xs">
                                <span class="glyphicon glyphicon-trash"> </span>
                            </button>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="text-center">
                        <div class="col-xs-9">
                            <h6 class="text-right">Added items?</h6>
                        </div>
                        <div class="col-xs-3">
                            <button type="button" class="btn btn-default btn-sm btn-block">
                                Update cart
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row text-center">
                    <div class="col-xs-9">
                        <h4 class="text-right">Total <strong>€50.00</strong></h4>
                    </div>
                    <div class="col-xs-3">
                        <button type="button" class="btn btn-success btn-block">
                            Weiter
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>