<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype();
$this->headScript()->appendFile($this->baseUrl('/js/site.js'));
?>
<html lang="de">
    <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <script type="text/javascript" async  data-pin-hover="true" src="//assets.pinterest.com/js/pinit.js"></script>
        <link rel="shortcut icon" href="/img/camera.ico" type="image/x-icon" />
        <meta property="og:type"   content="article" />
        <meta property="og:title"  content="Luftsprung" />
    </head>
    <body>
        <div class="container-fixed">
            <div class="row" style="padding: 0 15px; margin-left: 0px; margin-right: 0px;">
            <div class="hidden-xs">
                <a href="/">
                <img src="/img/banner.jpg" style="width: 100%" data-pin-no-hover="true">
                </a>
            </div>
            <nav class="navbar navbar-default" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--
                    <a class="navbar-brand" href="/">Luftsprung Photografie</a>
                    -->
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <?php
                    $options = array('ulClass' => '', 'maxDepth' => 2);
                    $mainmenu = $this->navigation()->findOneByClass('nav');
                    echo $this->navigation()
                            ->menu()
                            ->renderPartial(
                                    $this->navigation()->findOneByClass('nav'), array('navi.phtml', 'default')
                    );
                    ?>
                </div>
            </nav>
            <div class="col-md-12">
                <div class="row">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <?php
            $fm = new Zend_Controller_Action_Helper_FlashMessenger();
            $messages = array_merge($fm->getMessages(), $fm->getCurrentMessages());
            $fm->clearCurrentMessages();
            if (count($messages)) {
                foreach ($messages as $msg) {
                    ?>
                    <div class='notifications top-right' data-message='<?php echo $msg; ?>'></div>
                    <?php
                }
            }
            ?>
            </div>
        </div>
    </body>
</html>
