<?php
$navigation = Zend_Registry::get('nav');
$oGalleries = $navigation->findAllBy('route', 'gallery');
?>
<div class="row lightbox">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-3">
                <div class="list-group">
                    <?php foreach ($oGalleries as $gallery): ?>
                        <a href="#" class="list-group-item"><?php echo $gallery->label; ?></a>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="col-md-9">
                <div class="col-md-12">
                    <textarea></textarea>
                </div>
            </div>
        </div>
    </div>
</div>
