<div class="row lightbox">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-4">
                <div id="tree"></div>
            </div>
            <div class="col-md-8">
                <div class="col-md-12" id="shootings">

                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="galleryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>

<div class="modal fade" id="filemanagerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body" style="padding:0px; margin:0px; width: 560px;">
                <iframe width="560" height="400" src="/filemanager/dialog.php?type=1&amp;field_id=preview&amp;relative_urls=0" frameborder="0" style="overflow: scroll; overflow-x: hidden; overflow-y: scroll; "></iframe>
            </div>
        </div><!-- /.modal-content -->
    </div><
</div>