<div class="modal-dialog preview">
    <div class="modal-content">
        <form method="POST">
            <input type="hidden" name="gid" value="<?php echo $this->entry->getId();?>" />
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Vorschau <?php echo $this->entry->getTitle(); ?></h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <?php
                for($i=1;$i<=4;$i++)
                {
                ?>
                <div class="col-xs-3 col-md-3">
                    <div  class="thumbnail">
                        <?php
                        $sPreview = "";
                        if(($this->entry->Preview($i)) != "") {
                            $sPreview = "/images/".$this->entry->getPath()."/".$this->entry->Preview($i);
                        }
                        ?>
                        <img src="<?php echo $sPreview;?>" alt="">
                        <div class="caption">
                            <select class="form-control selectpicker" name="preview[<?php echo $i;?>]">
                                <option value="">Bild wählen</option>
                                <?php
                                foreach ($this->entry->pictures as $pic) {
                                    
                                    if($this->entry->Preview($i) == basename($pic['original'])) {
                                        ?>
                                        <option selected='selected'><?php echo basename($pic['original']);?></option>
                                        <?php
                                    } else {
                                        ?>
                                        <option><?php echo basename($pic['original']);?></option>
                                        <?php
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>
                <?php
                }
                ?>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
        </form>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->