<table class="datatable table table-striped table-bordered">
    <thead>
        <tr>
            <th>Datum</th>
            <th>Titel</th>
            <th>Pfad</th>
            <th>Teaser</th>
            <th>Aktiv</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $aActive = array("Inaktiv", "Aktiv");
        foreach ($this->entries as $entry) {
            echo "<tr>";
            printf("<td><a href='#' class='editable' data-type='date' data-name='created' data-title='Erstellungsdatum' data-type='text' data-pk='%d'>%s</a></td>", $entry->id, $entry->created);
            printf("<td><a href='#' class='editable' data-type='text' data-name='title' data-title='Titel' data-type='text' data-pk='%d'>%s</a></td>", $entry->id, $entry->title);
            printf("<td><a href='#' class='editable' data-type='select' data-name='path' data-title='Pfad' data-type='text' data-pk='%d' data-value='%s' data-source='/admin/getpaths'>%s</a></td>", $entry->id, $entry->path, $entry->path);
            printf("<td><a href='#' class='editable' data-type='textarea' data-name='teaser' data-title='Teaser' data-type='text' data-pk='%d'>%s</a></td>", $entry->id, $entry->teaser);
            printf("<td><a href='#' class='editable' data-type='select' data-source='%s' data-name='active' data-value='%s' data-emptytext='inaktiv' data-title='Active' data-type='select' data-pk='%d'>%s</a></td>", '[{value: "1", text: "Aktiv"},{value: 0, text: "Inaktiv"}]', $entry->active,$entry->id,  $aActive[$entry->active]);
            echo "</tr>";
        }
        ?>
    </tbody>
</table>

<h2>Neuer Eintrag</h2>

<table id="user" class="table table-bordered table-striped">
    <tbody> 
        <tr>         
            <td>Titel</td>
            <td><a href="#" class=" editable new" data-type="text" data-name="title" data-mode="inline" data-original-title="Enter firstname"></a></td>
        </tr>  
        <tr>         
            <td>Pfad</td>
            <td><a href="#" class=" editable new" data-type="select" data-name="path" data-mode="inline" data-source="/admin/getpaths" data-original-title="Welche Bilder sollen angezeigt werden"></a></td>
        </tr>     
        <tr>         
            <td>Teaser</td>
            <td><a href="#" class=" editable new" data-type="textarea" data-name="teaser" data-mode="inline" data-original-title="Ein kurzer Text zum Shooting" style="background-color: rgba(0, 0, 0, 0);"></a></td>
        </tr>
        <tr>         
            <td width="40%">Datum</td>
            <td><a href="#" class=" editable new" data-type="date" data-name="created" data-viewformat="dd/mm/yyyy" data-original-title="Shootingdatum eingeben"></a></td>
        </tr>
        <tr>         
            <td width="40%">Aktiv</td>
            <td><a href="#" class=" editable new" data-type="select" data-source="[{value: '1', text: 'Aktiv'},{value: '0', text: 'Inaktiv'}]" data-name="active" data-value="0" data-viewformat="dd/mm/yyyy" data-original-title="News anzeigen"></a></td>
        </tr>
    </tbody>
</table>
<button id="save-btn" class="btn btn-primary">Eintragen</button>

<dl class="dl-horizontal">
  <dt>Fett</dt>
  <dd>[b]foo[/b]</dd>
  <dt>Link</dt>
  <dd>[url="http://www.google.de" title="Google"]Hier gehts zu google[/url]</dd>
  <dt>Bild</dt>
  <dd>[img]http://url.zum/bild.jpg[/img]</dd>
</dl>